apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.aliyun.com/acr-instance-id: cri-3fynibeigjxpi5o6
  name: web-deployment
  namespace: {NAMESPACE}
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: user
        image: xom-ecomm-acr02-registry-vpc.cn-shanghai.cr.aliyuncs.com/tootest/ch-web:GITHUB_SHA
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
   
