apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: "lb-uf60e51dfzm6lzye1chhb"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-force-override-listeners: "true"
  name: web-service
  namespace: {NAMESPACE}
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
  - port: 1155
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
